package com.hid;

import com.hidglobal.ia.service.transaction.CancelationReason;

public class ApproveSDKConstants {
	public final static int MAX_BIO_ATTEMPTS = 3;
	public final static String BIOMETRIC_PROMPT_TITLE = "Use your fingerprint for fast and easy access to you account";
	public final static String BIOMETRIC_PROMPT_SUBTITLE = "Confirm fingerprint to continue";
	public final static String SIGN_TRANSACTION_FLOW = "SIGN_TRASACTION";
	public final static String NOTIFICATION_FLOW = "NOTIFICATION_FLOW";
	public final static String TS_VALUES_SEPERATOR = "~";
	public final static String LOG_TAG = "ApproveSDKWrapper";
	public final static String PWD_PROMPT_PROGRESS_EVENT_TYPE = "Progress";
	public final static String PWD_PROMPT_ERROR_EVENT_TYPE = "Error";
	public final static String PWD_PROMPT_PROGRESS_EVENT_CODE = "5000";
	public final static String PWD_PROMPT_ERROR_EVENT_CODE = "5001";
	public final static String PWD_EXPIRED_PROMPT_EVENT_CODE = "5002";
	public final static String PWD_EXPIRED_EXCEPTION = "PasswordExpiredException";
	public final static String AUTHENTICATION_EXCEPTION = "AuthenticationException";
	public final static String TRANSACTION_EXPIRED_CODE = "1000";
	public final static String TRANSACTION_EXPIRED_EXCEPTION = "TransactionExpiredException";
	public final static String BIOMETRIC_ERROR = "BiometricError";
	public final static String BIOMETRIC_FAILED = "BiometricFailed";
	public final static String UNSUPPORTED_DEVICE_EXCEPTION = "UnsupportedDeviceException";
    public final static String LOST_CREDENTIALS_EXCEPTION = "LostCredentialsException";
    public final static String INTERNAL_EXCEPTION = "InternalException";
    public final static String INVALID_PARAMETER_EXCEPTION = "InvalidParameterException";
    public final static String UNSUPPORTED_DEVICE_CODE = "200";
    public final static String LOST_CREDENTIALS_CODE = "106";
    public final static String INTERNAL_EXCEPTION_CODE = "0";
    public final static String INVALID_PARAMETER_CODE = "3";
	public final static String BIOMETRIC_ERROR_CODE = "5003";
	public final static String BIOMETRIC_FAILED_CODE = "5004";
	public final static String GENERIC_ERROR_CODE = "6000";
	public final static String NO_EXCEPTION_CODE = "2000";
	public final static String AUTH_EXCEPTION_CODE = "5001";
	public final static String FINGERPRINT_EXCEPTION = "FingerprintException";
	public final static String BIO_AUTH_NOT_ENABLED = "NoBioAuth";
	public final static String Success_Message = "success";
	public final static String No_Exception = "No Exception";
	public final static String GENERIC_EXCEPTION = "Exception";
	public final static String BIO_PROMPT_TITLE_PUSH_FLOW = "Use your fingerprint to view the transaction";
	public final static String BIO_PROMPT_TITLE_TS_FLOW = "Use your fingerprint to complete the transaction";
	public final static String BIO_PROMPT_DELETE_USER = "Use your fingerprint to delete your profile";
	public final static String BIO_ALREADY_ENROLLED = "because it is enabled by another user in this device";
	public final static String CONTAINER_FLOW_IDENTIFIER = "dty";
	public final static String AC_USERID_KEY = "userid";
	public final static String AC_SERVICE_KEY = "serviceurl";
	public final static String AC_INVITE_CODE_KEY = "invitecode";
	public final static String TOTP_KEY = "totp";
	public final static String DEVICE_ID = "deviceid";
	public final static String CODE_SECURE = "secure";
	public final static String CODE_SIGN = "sign";
	public final static CancelationReason CANCELATION_REASON_CANCEL = CancelationReason.USER_CANCEL;
	public final static CancelationReason CANCELATION_REASON_SUSPICIOUS = CancelationReason.NOTIFY_SUSPICIOUS;
}
